Update cron.yml

diff --git a/.github/workflows/cron.yml b/.github/workflows/cron.yml
--- a/.github/workflows/cron.yml
+++ b/.github/workflows/cron.yml
@@ -21,8 +21,8 @@ jobs:
         run: |
           nextAW=`curl -L --silent https://phpsecu.re/api/registry/workflow | grep '^{' | jq -r .need_workflow[0]`
           if [[ "$nextAW" == "" || "$nextAW" == "null" ]]; then echo "[INFO] No workflow in queue"; exit 0; fi
-          nextURL=`echo "$nextAW" | jq  -r .workflow_url`;
-          if [[ "$nextURL" == "" || "$nextURL" == "null" ]]; then echo "[ERROR] No workflow_url, JSON chunk: $nextAW"; exit 1; fi
+          nextURL=`echo "$nextAW" | jq  -r .app_path`;
+          if [[ "$nextURL" == "" || "$nextURL" == "null" ]]; then echo "[ERROR] No app_path, JSON chunk: $nextAW"; exit 1; fi
           nextSlug=`echo "$nextAW" | jq  -r .slug`;
           if [[ "$nextSlug" == "" || "$nextSlug" == "null" ]]; then echo "[ERROR] No slug, JSON chunk: $nextAW"; exit 1; fi
           nextRepo=`echo "$nextAW" | jq  -r .repo`;
